minimumReleaseAge: 0

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - '@octokit/endpoint@9.0.6'
  - chokidar@4.0.3
  - prettier-plugin-tailwindcss@0.7.4
  - semver@5.7.2 || 6.3.1

packages:
  # Web and Python packages
  - packages/*
  # Rust crates
  - crates/basis
  - crates/rustlings
  - crates/exercism/*

allowBuilds:
  esbuild: false
  msw: false
  nx: false
